[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables can be set here or in Netlify dashboard
# [build.environment]
#   NODE_VERSION = "18"

# Optional: Functions configuration if using Netlify Functions
# [functions]
#   directory = "netlify/functions"